### ISSUE TITLE
Ссылка

### ISSUE THREAD

**Issue by 4val0v** [geekbrains-manchenkov/SQL-tasks#1]
Можете дать ссылку на курс ?

**Comment by manchenkoff** [comment]
ссылка доступна только для участников

**Comment by 4val0v** [comment]
Я имел ввиду на сам курс чтобы ссылка привела меня в нужный раздел на geekbrains, так как на сайте есть множество курсов, а интересен этот

**Comment by manchenkoff** [comment]
https://geekbrains.ru/courses/161
